title: Blog Bibliotheks- und Archivinformatik
author: Alexandra Köchling

description: > # this means to ignore newlines
  Lerntagebuch Alexandra Köchling im Kurs Bibliotheks- und Archivinformatik FS2020

# social links



show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
